"""Sync the console's React islands from the abstractuic kit.

The console is HTML served from Python (no npm build at serve time), yet its
theme selector and connect/disconnect control must be the kit's REAL
components (operator order: "reuse the widgets from abstractuic
for the theme selector and connect/disconnect"). The kit builds them into
one self-contained IIFE (`ui-kit/scripts/build_islands.mjs` ->
`ui-kit/islands/dist/af-console-islands.js`, defining
`window.AfConsoleIslands`); this module vendors that bundle, plus the kit's
component CSS, into the GENERATED `console_islands.py`.

The copy is a packaging necessity (a wheel carries no kit checkout). It can
never rot silently: the generated module records a hash of every kit source
that feeds the bundle, and `tests/test_gateway_console_islands_sync.py`
recomputes it from the kit checkout (and byte-compares the bundle when the
kit has been built) — a kit change without a re-sync fails loud.

Run from the monorepo (abstractuic beside abstractgateway, or set
ABSTRACTUIC_SRC to the kit's ui-kit/src directory, as for the theme sync):

    (cd abstractuic/ui-kit && node scripts/build_islands.mjs)
    python -m abstractgateway.console_islands_sync
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import Dict, Optional

from .console_theme_sync import parse_theme_css_blocks

GENERATED_MODULE = "console_islands.py"
BUNDLE_RELPATH = Path("islands") / "dist" / "af-console-islands.js"
ISLANDS_API_VERSION = "1"

# Every kit file whose change can change the bundle or its CSS.
# src/*.json: the AbstractFramework identity descriptor ships inside the bundle.
_SOURCE_GLOBS = ("src/*.ts", "src/*.tsx", "src/*.json", "src/theme.css", "islands/*.tsx", "scripts/build_islands.mjs")


def locate_kit(repo_root: Optional[Path] = None) -> Optional[Path]:
    """The kit's ui-kit directory: the parent of ABSTRACTUIC_SRC (the same
    ui-kit/src seam console_theme_sync reads), else the abstractuic checkout
    beside this repo (monorepo layout)."""
    env = str(os.getenv("ABSTRACTUIC_SRC") or "").strip()
    if env:
        p = Path(env).expanduser().parent
        return p if (p / "package.json").is_file() else None
    root = repo_root if repo_root is not None else Path(__file__).resolve().parents[3]
    candidate = root / "abstractuic" / "ui-kit"
    return candidate if (candidate / "package.json").is_file() else None


def kit_version(kit: Path) -> str:
    return str(json.loads((kit / "package.json").read_text(encoding="utf-8")).get("version") or "")


def kit_sources_sha256(kit: Path) -> str:
    """One hash over the kit files that feed the islands (sorted, path-tagged)
    plus the kit version (the bundle banner carries it)."""
    h = hashlib.sha256()
    h.update(f"version:{kit_version(kit)}\n".encode("utf-8"))
    files = sorted({p for pattern in _SOURCE_GLOBS for p in kit.glob(pattern) if p.is_file()})
    for p in files:
        h.update(f"file:{p.relative_to(kit).as_posix()}\n".encode("utf-8"))
        h.update(p.read_bytes())
        h.update(b"\n")
    return h.hexdigest()


def kit_component_css(theme_css_text: str) -> str:
    """The kit's theme.css WITHOUT its per-theme `:root.theme-*` blocks —
    those already reach the console through console_themes.py (one copy of
    each block, not two). What stays: the base token block and every
    `.af-*` component rule the islands render (topbar, select, appearance)."""
    out = theme_css_text
    for _selector, block in parse_theme_css_blocks(theme_css_text):
        out = out.replace(block, "", 1)
    # Comments are the kit's design notes, not styles: drop them (and the
    # blank runs they leave) so the served page carries rules only.
    out = re.sub(r"/\*.*?\*/", "", out, flags=re.S)
    out = re.sub(r"\n\s*\n+", "\n", out)
    return out.strip() + "\n"


def generate_console_islands_module(kit: Path) -> str:
    bundle_path = kit / BUNDLE_RELPATH
    if not bundle_path.is_file():
        raise FileNotFoundError(f"{bundle_path} not built — run `node scripts/build_islands.mjs` in {kit}")
    bundle = bundle_path.read_text(encoding="utf-8")
    version = kit_version(kit)
    if not bundle.startswith(f"/*! @abstractframework/ui-kit {version} console islands"):
        raise ValueError(f"{bundle_path} was built from another kit version than {version}; rebuild it")
    css = kit_component_css((kit / "src" / "theme.css").read_text(encoding="utf-8"))
    provenance: Dict[str, str] = {
        "kit_version": version,
        "api_version": ISLANDS_API_VERSION,
        "kit_sources_sha256": kit_sources_sha256(kit),
        "bundle_sha256": hashlib.sha256(bundle.encode("utf-8")).hexdigest(),
        "css_sha256": hashlib.sha256(css.encode("utf-8")).hexdigest(),
    }
    prov_literal = json.dumps(provenance, ensure_ascii=False, indent=4)
    return (
        '"""GENERATED by console_islands_sync — DO NOT EDIT.\n'
        "\n"
        "Source of truth: abstractuic ui-kit (islands/console_islands.tsx built by\n"
        "scripts/build_islands.mjs, and src/theme.css minus the per-theme blocks\n"
        "that console_themes.py already carries). The console mounts the kit's\n"
        "AfTopBarActions + AfAppearanceDialog from ISLANDS_JS. Regenerate with:\n"
        "    (cd abstractuic/ui-kit && node scripts/build_islands.mjs)\n"
        "    python -m abstractgateway.console_islands_sync\n"
        "The drift pin (test_gateway_console_islands_sync.py) fails loud when\n"
        "this file is stale against the kit checkout.\n"
        '"""\n'
        "\n"
        "# fmt: off\n"
        f"ISLANDS_PROVENANCE = {prov_literal}\n"
        "\n"
        f"ISLANDS_CSS = {css!r}\n"
        "\n"
        f"ISLANDS_JS = {bundle!r}\n"
        "# fmt: on\n"
    )


def sync(target_dir: Optional[Path] = None) -> Path:
    kit = locate_kit()
    if kit is None:
        raise FileNotFoundError(
            "abstractuic ui-kit not found — set ABSTRACTUIC_SRC to the ui-kit/src "
            "directory or run from the framework monorepo checkout"
        )
    out_dir = target_dir if target_dir is not None else Path(__file__).resolve().parent
    out = out_dir / GENERATED_MODULE
    out.write_text(generate_console_islands_module(kit), encoding="utf-8")
    return out


if __name__ == "__main__":
    print(f"wrote {sync()}")
